install:
  - ps: >
      if ($env:PYTHON) {
        # Для Windows
        $env:PATH = "$env:PYTHON;$env:PATH"
      } else {
        # Для Linux
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
      }
  - pip3 install flask
  - pip3 install gunicorn
before_install:
  - chmod +x ./flaskapp/st.sh
build: off  # Отключаем сборку, так как это не требуется для Python
test_script:
  - cd flaskapp
  - ./st.sh
